# Statistical Approach 

## Overview

All analyses on the site are conducted with the [`metafor`](http://www.metafor-project.org/doku.php) package (Viechtbauer, 2010). 

## Effect Size Computation

Effect size computation is handled by a script, [`compute_es.R`](https://github.com/langcog/metalab2/blob/master/scripts/compute_es.R).

Several pre-existing MAs deal with special cases, and these are listed in the script. 

Except where noted, formulas are from [Hedges & Olkin's textbook](http://www.amazon.com/Statistical-Methods-Meta-Analysis-Larry-Hedges/dp/0123363802). 

## Statistical Models

The visualizations page uses a multi-level random effects meta-analysis ( `rma.mv` function of `metafor`).
Random-effect models assume that the true effect can vary between different studies, and therefore allow
random effects for each data point. The model also specifies random effects on the level of each paper, since studies within a paper can be assumed to be more similar to each other than to studies from different papers. In addition, we allow correlated random effects within each paper to account for cases where the same infants contributed data to multiple rows. 

The meta-analytic models are accessible in the script [`server.R`](https://github.com/langcog/metalab2/tree/master/shinyapps/visualization/server.R)
