---
title: Contribute existing MA
date: 2020-07-26
type: book
---


Contribute your meta-analysis
=============================================================

If you have already done a meta-analysis, you can easily add it to MetaLab. This tutorial explains how. But first, we go over why this is good for you and the community.

### Why should I contribute my meta-analysis to MetaLab?

Contributing to MetaLab can have several advantages both for you and the community:  
* **Get more visibility for your MA.** When publishing a paper, you wish that it will be read by as many people as possible. Placing it in a centralized repository such as MetaLab can help you to reach this broad audience and gives more visibility to your meta-analysis.  
* **Increase the impact of your MA.** As an author, you probably want your results to be fully understood by readers, and you want your readers to use your data as efficiently as possible. The interactive interface of the MetaLab website allows readers to better navigate in your meta-analysis results than the paper version, and to play with the results to better use them when planning experiments. MetaLab is an opportunity for your meta-analysis to make a stronger impact.  
* **Contribute to drawing the broader developmental picture.** You made a meta-analysis to help the community draw a clearer picture about an effect of interest and contribute to theory assessment. MetaLab is a central platform that includes over 1040 effect sizes. Incorporating your meta-analysis in this larger dataset helps the community to have a better idea of cognitive development and language acquisition.

### Who owns the data contributed to MetaLab? 

You remain the owner of your meta-analysis data: Users must cite your data by your preferred citation. If your data are previously unpublished then this doesn't count as publication. Learn more by reading our [full citation policy](/publications.html). 

### Can I retain control on my data? Must I forever retain control of my data?

You can retain control for as long as you want to. In fact, two options exists for the curation and review of your data. You can **choose to be the curator**. This means you agree to be the person responsible for identifying new relevant papers and signaling them to the MetaLab data manager, who will add them to the database of the relevant MA. You would be expected to check data entry once in a while. Curators are part of the MetaLab board and get informed of discussions regarding e.g. site revamping. Alternatively, you can **choose to step down completely**, and it will be MetaLab’s job to assign a new curator for your dataset. In this case, we can still keep your photo on the wall of fame.

### How do I code my existing meta-analysis in the MetaLab format ? 

We prepared a [spreadsheet](https://docs.google.com/spreadsheets/d/12Y_2BcFSu48t0F8a_xrY1Ro2fJoCIV1h8O627WNcrjY/edit#gid=0) that you must use to code your data. The key property of this spreadsheet is that it has one row for each effect size. Therefore you should fill as many rows as the number of effect size you report in your meta-analysis.   
* The first tab, called “Data”, should contain your data.   
* The second tab, called “CodeBook”, contains all the explanations about the codes to be used when you fill the “Data” tab.   
* The third tab, called “Methods”, contains all the possible options for the “method” column and their respective description. 

Follow these steps to convert your data:   

1. Make a copy of the spreadsheet.  
2. Rename the copy  with an informative name to identify your MA: FirstAuthor_Topic (e.g. Dunst_motionese_preference).  
3. Create a new tab and copy-paste your data table there.  
4. Make a copy of the “Data” tab to keep an interim version of your data.  
5. Copy the first column of the tab containing your data table. Then go to the new “InterimData” tab and paste your first column in the MetaLab column that matches.   
6. Repeat step 5 for each column of your data table.  
7. Copy the first column of the “InterimData” in the “Data” tab. Then edit each cell to match the data format specified in the “CodeBook” tab.  

If you work from your paper, you may have an appendix or a table for each of your moderators. In this case, take them one by one and follow these steps:  

1. Create a tab and copy-paste your appendix or table there. Check that the content of your appendix hasn’t been messed up when pasting. Rename the tab with the name of your moderator.
2. Edit the data to have one row per effect size. 
3. If you have several tables/appendix, repeat step 1-2 for each of them.
4. If you have several appendix create another tab and copy paste the content of all appendix-specific tabs side-by-side to check that all lines match up (i.e. same number of effect sizes in all the appendix/tables).
5. Once you have synthesized all your appendix in one table, copy-paste the column corresponding to a MetaLab requirement in the “Data” tab and edit each cell to match the data format specified in the “CodeBook” tab.   

### What if an effect size is computed with groups from two different papers ?

Write the two references in each of the first three columns (study_ID, long_cite, short_cite), separated by commas. The “short cite columns” should be in the text citation format, i.e. Smith (2002, 2008), if the two papers are from the same authors. 
Fill the other columns as usual. 

### What if I don’t have all the columns required by MetaLab ?

Fill the missing columns with “NA”. If it happens that you don’t have one of the mandatory columns, please [let us know](metalab-project@googlegroups.com).

### What types of communications are considered as peer-reviewed ?

Most journal articles are peer-reviewed; some conference proceedings (e.g., Cognitive Science) are peer-reviewed. Typically, book chapters, posters, and conference abstract are not considered peer-reviewed because no reviewer has seen the full details of the methods.
