---
title: How to Contribute
date: 2020-07-26
type: book
---


We welcome researchers interested in contributing to Metalab. Please contact us at metalab-project@googlegroups.com

Contributions can take various forms:

1. Adding unpublished data. Ideally we can link to a report on the data, for example on [OSF](http://osf.io). Then contact the curator
with a link and if possible all necessary data.
2. Suggesting and/or adding published papers not yet included. Simply email the curator, ideally with a pdf. If you are the author, try to make sure that all necessary data is either included or provided in your email.
3. Creating new meta-analyses. You can either collaborate on current in-progress projects (see below) or create your own meta-analyses. In the latter case see the section listing resources further down.

**New meta-analyses looking for contributors**

Currently, the following topics are in the process of becoming a meta-analysis and we are looking for contributors:

* Segmenting words from an artificial stream of speech, an extension of [*InWordDB*](http://inworddb.acristia.org); contact: [*Christina Bergmann*](http://sites.google.com/site/chbergma/home/contact)
* Detecting mispronunciations of known words, without a learning phase in the lab; contact: [*Christina Bergmann*](http://sites.google.com/site/chbergma/home/contact)


**Resources**

Here are a few resources on creating meta-analyses compatible with Metalab:

* [*Metalab MA template*](https://docs.google.com/spreadsheets/d/12Y_2BcFSu48t0F8a_xrY1Ro2fJoCIV1h8O627WNcrjY/edit?usp=sharing)
* [*Code book*](https://docs.google.com/document/d/1szXxrv75qTVx-4adlLrwmjWSDIBJfMH09dzh9733mog/edit?usp=sharing)
* [*Interrogating PubMed via a  script*](https://gist.github.com/mcfrank/c1ec74df1427278cbe53)
* [*Selecting studies for
inclusion*](https://www.getdatajoy.com/project/561388dfb485274e40055563)
* [*FAQ*](https://docs.google.com/document/d/1_7mgeaARlYK6TecyUqzk9SSr0pLAkV3pQZE4qYT7CMA/edit?usp=sharing)
* [*InWordDB, a well-fleshed out MA*](https://docs.google.com/spreadsheets/d/1XN6VaYRs7CStrINct_rr2d6rh6WN28xFiIGB5T1vkzY/edit?usp=sharing)
* [*Instructions for creating a
community-augmented meta-analysis*](https://sites.google.com/site/infantdbs/create-your-own-cama)
(including further resources)
