---
title: Effect Sizes
date: 2020-07-26
type: book
---


What are effect sizes?
======================

In MAs (meta-analyses) we express the outcome of a single experiment in a way that captures how big an effect is and how much it varies. There are 3 groups of effect sizes:   
1. effect sizes based on means, which includes Cohen's *d* on which we focus from here on;   
2. effect sizes based on binary data; and   
3. effect sizes based on correlations. 

Since most developmental studies in the lab use mean responses of two groups or of the same infant in two (or more) conditions, Cohen's d is the appropriate effect size measure. This [chapter 3](http://www.meta-analysis.com/downloads/Meta-analysis%20Choosing%20an%20effect%20size.pdf) and the following ones provide a gentle introduction to effect sizes. Cohen's d is based on standardized mean differences. To get a feel for Cohen's d we highly recommend to play with the [visualization](http://rpsychologist.com/d3/cohend/) of RPsychologist. A list of recommended readings is also provided at the end of this document.

In a typical infant study, babies might hear two types of trials and the responses to each are compared. In most papers, it is sufficient that the difference between the trial types reaches statistical significance, but in a meta-analyses we care about the size of this single observed effect and its variance. This allows us to pool over several studies, weigh each datapoint, and arrive at an estimate of the underlying, true effect. This then allows us to calculate power and check how effect sizes might be systematically affected by variables such as infant age in "moderator analyses". 

**Recommended further readings for an introduction to effect sizes**:

1. Textbooks are great to get a basic overview of how to calculate effect sizes. We consulted: Lipsey, M. W. & Wilson, D. B. (2001). Practical meta-analysis. Thousand Oaks, CA: Sage.  
2. A great primer and a spreadsheet document to calculate effect sizes by hand can be found via: D. Lakens. (2013). Calculating and Reporting Effect Sizes to Facilitate Cumulative Science: A Practical Primer for t-tests and ANOVAs . Frontiers in Psychology 4:863. [Materials on OSF](osf.io/ixgcd/files/)    
3. Since textbooks do not cover every possible question that different meta-analysts may encounter, we turned to articles for more specific questions. We found this article useful for considering the comparability of effect sizes from within- and between-participant designs: Morris, S. B., & DeShon, R. P. (2002). Combining Effect Size Estimates in Meta-Analysis With Repeated Measures and Independent-Groups Designs. Psychological Methods, 7(1), 1805-125. doi: 10.1037//1082-989X.7.1.105     
4. Borenstein, M., Hedges, L. V. ,Higgins,  J. P. T.,  Rothstein, H. R. (2009). Introduction to Meta-Analysis. John Wiley & Sons. DOI: 10.1002/9780470743386.ch3	
