---
title: Introduction
date: 2016-04-20
type: book
---

The Academic Website Builder enables you to easily create a beautifully simple website using the [Hugo](https://gohugo.io) static site generator in under 10 minutes 🚀

## First steps

To get the most out of Academic, start by reviewing a few introductory topics:

- [Create your site]({{< relref "install.md" >}})
- [Get Started]({{< relref "get-started.md" >}}), [Build your Homepage]({{< relref "page-builder.md" >}}), and [Customize]({{< relref "customization.md" >}}) your new site
- [Add content]({{< relref "managing-content.md" >}}) to your homepage such as blog posts, projects, talks, publications, slides, and much more!
- [Write and format content]({{< relref "writing-markdown-latex.md" >}}) with Markdown, math, code highlighting, galleries, third-party integrations, and much more!
- [Join the Academic community on Discord](https://discord.gg/z8wNYzb), [follow us on Twitter](https://twitter.com/source_themes), or [browse the Q&A](https://spectrum.chat/academic)
- ⭐️ [**Star** Academic on **GitHub**](https://github.com/gcushen/hugo-academic)
- {{< icon name="twitter" pack="fab" >}} [**Share your new site** with the Academic community](https://twitter.com/intent/tweet?text=I%27m%20creating%20a%20beautiful%20website%20using%20the%20Academic%20Website%20Builder%20for%20%40GoHugoIO%20by%20%40GeorgeCushen!&amp;hashtags=MadeWithAcademic&amp;url=https://sourcethemes.com/academic/)
- [Contribute]({{< relref "contribute.md" >}})

{{% alert thanks %}}
**We're full steam ahead on improving Academic, and we need your help!**

- :heart: [**Become a backer** on Patreon or GitHub]({{< relref "/plans.md" >}}) and **unlock [these]({{< relref "/plans.md" >}}) rewards and extra features**

{{% /alert %}}

## Why Academic?

Learn [why Academic was created and the benefits of using it to power your site](https://georgecushen.com/create-your-website-with-hugo/).

## A note on versions

The documentation on this site aims to track the _latest version_ of Academic. 

For _previous versions_ of Academic, one can travel back in time via the GitHub [repository for this site](https://github.com/sourcethemes/academic-www). Simply note the [date of your version](https://github.com/gcushen/hugo-academic/releases), and view the Markdown pages in the [repository for this site](https://github.com/sourcethemes/academic-www) shortly after that point in time.
