# Challenge contribution step by step

To celebrate the release of its new website, the MetaLab team with support of the Berkeley Initiative for Transparency in the Social Sciences [BITSS](http://bitss.org/) is organizing a challenge for authors of meta-analyses on cognitive development (i.e. concerning participants younger than 4 years of age). This challenge will offer a total of $3,000 US in cash to (teams of) authors who contribute their meta-analysis data to the MetaLab database. 

If you wish to participate, here are the steps that you should follow:

1. As soon as possible, sign up [here](https://docs.google.com/forms/d/1YtZr2gBulKdT7DkmHkUj1MPyjy_bwS6tDw1MigoOQ1Y/edit) to inform us that you wish to contribute and so that we send you important updates. 

2. Code your meta-analytic data using the [MetaLab template](https://docs.google.com/spreadsheets/d/12Y_2BcFSu48t0F8a_xrY1Ro2fJoCIV1h8O627WNcrjY/edit). You can add new columns for custom moderators.

3. Send your data spreadsheet, optional documents for bonus points (PRISMA flowchart, decision spreadsheet…), and your preferred citation to metalab-project@googlegroups.com at any time. 

## Data-sharing policy
Your meta-analysis will be added to the MetaLab online database. Therefore users will be able to download your data and potentially re-use it. You remain the owner of your meta-analysis data: MetaLab requires anyone who uses a dataset to cite the contributors of the dataset, even if there is no publication or pre-print yet. When submitting, please provide us with the citation that users should use, potentially specifying « in preparation », and/or linking to an online repository (such as OSF). Of course, this would be updated with the pre-print and finally with the publication. If your data are unpublished then your contribution to MetaLab doesn’t count as publication. Learn more by reading our [full citation policy](http://metalab.stanford.edu/publications.html).

MetaLab is dynamic: Meta-analysis can be updated, adding new relevant studies when they are published. You can retain control on this for as long as you want to. In fact, two options exists for the curation and review of your data. You can choose to be the curator. This means you agree to be the person responsible for identifying new relevant papers and signaling them to the MetaLab data manager, who will add them to the database of the relevant MA. You would be expected to check data entry once in a while. Curators are part of the MetaLab board and get informed of discussions regarding e.g. site revamping. Alternatively, you can choose to step down completely, and it will be MetaLab’s job to assign a new curator for your dataset. In this case, we can still keep your photo on the wall of fame.

**The challenge closes on June, 30**. You will be informed of the results of the challenge by email shortly after.

Please reach out to us if you have any questions.
