
```{r child='assets/setup.Rmd'}
```

```{r echo=FALSE}
menuNavbar()
```

```{r echo=FALSE}
people <- yaml::yaml.load_file(here("metadata", "people.yaml"))

renderMemberInfo <- function(memberInfo) {
  div(class = "box-pad", 
    shinydashboard::box(class = "box-content", width = NULL, align = "center", #status = "danger",
      solidHeader = TRUE,
      img(src = memberInfo$image, width = 180, height = 180),
      a(h4(strong(memberInfo$name)), href = memberInfo$website, target = "_blank"),
      memberInfo$affiliation,
      br(),
      if (!is.null(memberInfo$email)) a(memberInfo$email, href = sprintf("mailto:%s", memberInfo$email)),
      br(),
      tags$small(
        map(unlist(strsplit(if (is.null(memberInfo$databases)) {""} else {memberInfo$databases}, ", ")),
          ~list(code(.x, class = "red-code"), br())) %>%
        flatten()
        )
      )
    )
  }

renderGroupMembers <- function(memberStatus, peopleSet) {
  fullWidthPanelBox(memberStatus, purrr::map(peopleSet, renderMemberInfo))
}

tagList(map(names(people), ~renderGroupMembers(., people[[.]])))

fullWidthPanelBox(
  "Funding",
  p("Funding for this research was provided by the Berkeley Initiative for Transparency in Social Sciences and the Laura and John Arnold Foundation. We also thank RStudio for their education license of Shiny Server Pro.")
)

fullWidthPanelBox(
  "Source code",
  HTML("The source for this website can be found <a href='https://github.com/langcog/metalab2/'>on GitHub</a>. The website itself is hosted through GitHub Pages, with the accompanying visualizations hosted on a Shiny server.<br/><br/>Many thanks to <a href='https://deanattali.com/' target='_blank'>AttaliTech Ltd</a> for website redesign.")
)
```

```{r, echo=FALSE}
htmltools::includeHTML("footer.html")
```
