```{r child='assets/setup.Rmd'}
```

```{r echo=FALSE}
menuNavbar()
htmltools::tagList(
  rmarkdown::html_dependency_font_awesome(),
  rmarkdown::html_dependency_bootstrap(theme = "default"),
  rmarkdown::html_dependency_highlightjs(highlight = "default"))
htmltools::includeScript(here("pages", "assets", "custom.js"))
```

```{r echo=FALSE, warning=FALSE}
documentation <- yaml::yaml.load_file(here("metadata", "documentation.yaml"))
header <- "Documentation"
content <- do.call(tabBox,
      c(width = 12,
        purrr::map(documentation,
          ~ tabPanel(.$title,
              includeRmd(here("pages", "documentation", paste0(.$id, ".Rmd"))),
              value = .$id)
          )
        ))

fluidRow(
    column(width = 2),
    column(width = 8,
           fluidRow(style = "border-color: #dd4b39;",
                    div(h3(header)),
                    div(style = "color: #444;", content)
           )
    ),
    column(width = 2)
  )
```

```{r, echo=FALSE}
htmltools::includeHTML("footer.html")
```
