---
params:
  dataset: !r data.frame(short_name=character(2), num_papers=integer(2), num_experiments=integer(2), num_subjects=integer(2), stringsAsFactors = FALSE)
  domainName: !r yaml::yaml.load_file("../metadata/domains.yaml")[[1]]$title
---

<style>body {background-color: #ecf0f5;}</style>

```{r child='assets/setup.Rmd'}
```

```{r tools, echo=FALSE}
datasetBox <- function(i, data) {
  data <- data[i, ]
  box(
    width = 12, #status = "danger",
    solidHeader = TRUE,
    fluidRow(class = "data-box",
      column(width = 3,
        img(src = paste0("../", data$src), width = "100%", class = "dataset-img")),
      column(width = 9, class = "dataset-txt",
        h4(strong(data$name)), p(data$short_desc)))
  )
}
```

```{r echo=FALSE}
menuNavbar("../")
```

```{r header, echo=FALSE}
fluidRow(
  column(width = 12,
    h1(class = "domain-header", params$domainName),
    fluidRow(class = "domain-boxes",
      column(width = 5, 
        valueBoxes(
          params$dataset %>% metricsCounter)
        ),
      column(width = 7))
    )
  )

if (nrow(params$dataset) > 1) {
  fluidRow(
    column(width = 1),
    column(width = 5, class = "cont-dom",
      map(seq(1, ceiling(nrow(params$dataset) / 2), 1),
        ~ a(class = "no-format",
            href = paste0("../dataset/", params$dataset[["short_name"]][[.]], ".html"),
            datasetBox(., params$dataset))
        )
      ),
    column(width = 5, class = "cont-dom",
      map(seq(ceiling(nrow(params$dataset) / 2 + 1), nrow(params$dataset), 1),
        ~ a(class = "no-format",
            href = paste0("../dataset/", params$dataset[["short_name"]][[.]], ".html"),
            datasetBox(., params$dataset))
        )
      ),
    column(width = 1)
  )
} else {
  fluidRow(
    column(width = 1),
    column(width = 10,
      a(class = "no-format",
        href = paste0("../dataset/", params$dataset$short_name, ".html"),
        datasetBox(1, params$dataset))
      ),
    column(width = 1)
    )
  }
```
