
```{r child='assets/setup.Rmd'}
```

```{r tools, echo=FALSE}
domainBox <- function(i, data_domains, offsets, link) {
  data <- data_domains[[i]]
  fluidRow(
    if (!offsets[1] == 0) {column(width = offsets[1])},
    box(
      width = 12 - sum(offsets), #status = "danger",
      solidHeader = TRUE,
      a(href = link, class = "no-format",
        fluidRow(class = "domain-box",
          column(width = 4,
            img(src = data$image, width = "100%", class = "dataset-img")),
          column(width = 8, class = "dataset-txt",
            h4(strong(data$title)), p(data$desc))
          )
        )
      ),
    if (!offsets[2] == 0) {column(width = offsets[2])}
    )
}
```


```{r header, echo=FALSE, warning=FALSE}
div(class = "text-center",
  fluidRow(
    column(width = 12,
      h1("MetaLab", class = "jumbo"),
      p(class = "lead",
            "Interactive tools for community-augmented meta-analysis,", br(),
            "power analysis, and experimental planning in cognitive development research")
      )
    )
  )

menuNavbar(isIndex = TRUE)

fluidRow(class = "domain-info",
         column(width=1),
         column(width = 10, style = "font-size:100%", br(),
                "To celebrate the release of the new website, the MetaLab team with support of the Berkeley Initiative for Transparency in the Social Sciences",
                tags$a(href = "https://www.bitss.org/", "(BITSS)"), 
"is organizing a challenge for authors of meta-analyses on cognitive development. This challenge will offer a total of $3,000 US in cash prizes to (teams of) authors who contribute their meta-analysis data to the MetaLab database. If you wish to participate, here are the steps that you should follow:",
                br(),
                HTML("<ol>
                        <li>As soon as possible, sign up <a href = 'https://docs.google.com/forms/d/1YtZr2gBulKdT7DkmHkUj1MPyjy_bwS6tDw1MigoOQ1Y/viewform?edit_requested=true'>here</a> to inform us that you wish to contribute and so that we may send you important updates.</li>
                        <li>Code your meta-analytic data using the <a href = 'https://docs.google.com/spreadsheets/d/12Y_2BcFSu48t0F8a_xrY1Ro2fJoCIV1h8O627WNcrjY/edit#gid=0'>  MetaLab</a> template.</li>
                        <li>Send us your data spreadsheet and optional documents for bonus points (PRISMA flowchart, decision spreadsheet, etc.) to metalab-project@googlegroups.com at any time. We will check it and get back to you to confirm that your contribution is accepted as well as give you feedback on your submission.</li>
                        <li>The challenge closes on June 30, 2018. You will be informed of the results of the challenge by email shortly after.</li>
                     </ol>"), br()))

div(
  fluidRow(
    column(width = 1),
    column(width = 3,
      tags$a(href = paste0("app.html?id=", "visualization"),
        div(class = "thumbnail",
          tags$img(src = "images/apps/visualization-wide.png"),
          div(class = "caption",
            h4("Meta-analytic Visualizations")
          )
        )
      )
    ),
    column(width = 3,
      tags$a(href = paste0("app.html?id=", "power_analysis"),
        div(class = "thumbnail",
          tags$img(src = "images/apps/power_analysis-wide.png"),
          div(class = "caption",
            h4("Power Analysis")
          )
        )
      )
    ),
    column(width = 4, class = "content-info",
      "You can explore the data with", 
      tags$a(href = "analyses.html", "interactive visualization tools."), 
      br(),
      br(),
      "If you are interested in contributing, please visit our", 
      tags$a(href = "tutorials.html", "tutorials.")),
    column(width = 1)
  )
)

fluidRow(class = "domain-info",
  column(width = 6,
    map(seq(1, ceiling(length(domains) / 2), 1),
      ~ tagList(
        fluidRow(
          domainBox(., domains, c(2, 0), link = paste0("domain/", domains[[.]][["id"]], ".html"))),
        fluidRow(class = "left-part",
          column(width = 2),
          column(width = 10,
            valueBoxes(
              filter(ungroup(datasets), domain == domainIDs[[.]]) %>% metricsCounter)
            )
          )
        )
      )
    ),
  column(
    width = 6,
    map(seq(ceiling(length(domains) / 2 + 1), length(domains), 1),
        ~ tagList(
          fluidRow(
            domainBox(., domains, c(0, 2), link = paste0("domain/", domains[[.]][["id"]], ".html"))),
          fluidRow(class = "right-part",
            column(width = 10, valueBoxes(
              filter(ungroup(datasets), domain == domainIDs[[.]]) %>% metricsCounter)
              ),
            column(width = 2)
            )
          )
        )
    )
  )
```


