# How to contribute?

We welcome researchers interested in contributing to Metalab. Please contact us at metalab-project@googlegroups.com

Contributions can take various forms:

- *Suggesting and/or adding published papers* not yet included in a meta-analysis. If you see a study we missed, just email us, ideally including the pdf. If you are the author, try to make sure that all necessary data is either included or provided in your email.
- *Adding unpublished data to a meta-analysis.* Please email us and we will tell you how we can go about adding your unpublished data to our meta-analyses.
- *Creating new meta-analyses.* If you are interested in creating a new meta-analysis, check out the tutorial page [LINK].
- *Contribute existing meta-analyses.* If you already have a completed meta-analysis, make sure to use the MetaLab template [LINK] and get in touch about integrating it into MetaLab. 
  Regarding the ownership of your data, you remain the owner of your meta-analysis data, and researchers publishing or presenting work using data in MetaLab must cite the publications linked to your meta-analysis. 
  We currently offer two options for the meta-analysis maintenance and update: 
  - *Be the curator.* This means the following:
      - you are responsible for identifying new relevant papers (although the MetaLab data manager can add them for you) We recommend to set alerts for new papers on your meta-analysis topic. 
      - you should check data entry and correct it if needed once in a while. 
      - you ... Curators determine moderators to be displayed and are responsible of executive decisions regarding spreadsheet content. By default you will be the curator for one year. Each year we will send an email listing all the meta-analysis you are in charge of and asking you if you still want to be the curator of them. Curators are part of the MetaLab board and get informed of discussions regarding e.g. site revamping. 

  - *Step down completely,* and it will be MetaLab’s job to assign a new curator for your dataset. In this case, we can still keep your photo on the wall of fame.
  
  Check out the tutorial page on how to edit your meta-analysis in the MetaLab format. 
