# Statistical Approach 

## Overview

All analyses on the site are conducted with the [`metafor`](http://www.metafor-project.org/doku.php) package (Viechtbauer, 2010). 

## Effect Size Computation

Effect size computation is handled by a script, [`compute_es.R`](https://github.com/langcog/metalab2/blob/master/scripts/compute_es.R).

Several pre-existing MAs deal with special cases, and these are listed in the script. 

Except where noted, formulas are from [Hedges & Olkin's textbook](http://www.amazon.com/Statistical-Methods-Meta-Analysis-Larry-Hedges/dp/0123363802). 

## Statistical Models

The visualizations page uses a standard random effects meta-analysis as the default, but allows several other models (all available in the `rma` function of `metafor`). 

For many analyses, the use of a multi-level approach (with grouping by paper) is useful, and may make a difference to results. We have not made this multi-level model the default, for two reasons. First, the approach will be unfamiliar to many users. Second, many common statistics are not implemented for this model, e.g. $\tau^2$ and the test for funnel-plot asymmetry. 
